#custom_configs
add_newline = false

# format = """
# $directory(bold red) ($git_branch $git_state $git_status)[»](bold pink) """

format = """
$directory(bold red)($git_branch$git_state$git_status)[»](bold red) """


[git_branch]
style = "bold green"
format = "[\\[[$branch$tag](bold green)\\]](bold white)"

[git_status]
format = ' ([\[$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind\]]($style))'

[directory]
style = "bold cyan"
truncate_to_repo = false
truncation_length = 1
fish_style_pwd_dir_length = 1


[c]
format = "[via](bold pink) [$name $version]($style)"


[python]
scan_for_pyfiles = true

[ruby]
disabled = true

[swift]
disabled = true

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "bold red"

[username]
show_always = true
style_user = "bold green"
format = "[$user]($style)"

[time]
style = "bold green"
disabled = false
format = "[$time]($style)"
time_format = "%H:%M:%S"
